services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: cloudinarace
    restart: always
    tty: true
    environment:
      - CLOUDINARY_ID=${CLOUDINARY_ID}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
